"""initial_schema

Revision ID: bf3f254e8dba
Revises: 
Create Date: 2026-05-16 19:53:34.454339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf3f254e8dba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', 'GOOGLE', name='oauthprovider'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_username', sa.String(length=255), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oauth_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_workspaces_owner_id', 'workspaces', ['owner_id'], unique=False)
    op.create_index('ix_workspaces_slug', 'workspaces', ['slug'], unique=False)
    op.create_table('audit_events',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'WORKSPACE_CREATED', 'WORKSPACE_UPDATED', 'MEMBER_INVITED', 'MEMBER_REMOVED', 'REPOSITORY_CONNECTED', 'REPOSITORY_REMOVED', 'INCIDENT_CREATED', 'INCIDENT_UPDATED', 'ANALYSIS_STARTED', 'PATCH_APPLIED', 'SANDBOX_EXECUTED', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_actor_id', 'audit_events', ['actor_id'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_workspace_id', 'audit_events', ['workspace_id'], unique=False)
    op.create_table('repositories',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('clone_url', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.String(length=255), server_default='main', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INDEXING', 'READY', 'ERROR', 'ARCHIVED', name='repositorystatus'), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repositories_workspace_id', 'repositories', ['workspace_id'], unique=False)
    op.create_index('ix_repositories_ws_fullname', 'repositories', ['workspace_id', 'full_name'], unique=True)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='workspacerole'), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_members_ws_user', 'workspace_members', ['workspace_id', 'user_id'], unique=True)
    op.create_table('incidents',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='incidentseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.Column('raw_logs', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_created_by', 'incidents', ['created_by_id'], unique=False)
    op.create_index('ix_incidents_severity', 'incidents', ['severity'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_workspace_id', 'incidents', ['workspace_id'], unique=False)
    op.create_table('repository_files',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repository_files_repo_id', 'repository_files', ['repository_id'], unique=False)
    op.create_index('ix_repository_files_repo_path', 'repository_files', ['repository_id', 'file_path'], unique=True)
    op.create_table('repository_import_jobs',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='importjobstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('files_processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_jobs_repo_id', 'repository_import_jobs', ['repository_id'], unique=False)
    op.create_index('ix_import_jobs_status', 'repository_import_jobs', ['status'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='analysisrunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_runs_incident_id', 'analysis_runs', ['incident_id'], unique=False)
    op.create_index('ix_analysis_runs_status', 'analysis_runs', ['status'], unique=False)
    op.create_table('code_chunks',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(length=512), nullable=True),
    sa.Column('symbol_type', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_code_chunks_file_id', 'code_chunks', ['file_id'], unique=False)
    op.create_index('ix_code_chunks_symbol', 'code_chunks', ['symbol_name'], unique=False)
    op.create_table('analysis_steps',
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('EVIDENCE_GATHERING', 'ROOT_CAUSE_ANALYSIS', 'FIX_GENERATION', 'VALIDATION', name='analysissteptype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='analysisstepstatus'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_steps_run_id', 'analysis_steps', ['analysis_run_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Enum('LOG_SNIPPET', 'STACK_TRACE', 'CODE_REFERENCE', 'CONFIGURATION', 'METRIC', 'EXTERNAL_LINK', name='evidencetype'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_lines', sa.String(length=64), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_items_run_id', 'evidence_items', ['analysis_run_id'], unique=False)
    op.create_index('ix_evidence_items_type', 'evidence_items', ['evidence_type'], unique=False)
    op.create_table('patch_sets',
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'APPLIED', 'REJECTED', name='patchsetstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('diff_content', sa.Text(), nullable=False),
    sa.Column('files_changed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['applied_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patch_sets_run_id', 'patch_sets', ['analysis_run_id'], unique=False)
    op.create_index('ix_patch_sets_status', 'patch_sets', ['status'], unique=False)
    op.create_table('sandbox_runs',
    sa.Column('patch_set_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'PASSED', 'FAILED', 'ERROR', name='sandboxrunstatus'), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patch_set_id'], ['patch_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandbox_runs_patch_set_id', 'sandbox_runs', ['patch_set_id'], unique=False)
    op.create_index('ix_sandbox_runs_status', 'sandbox_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sandbox_runs_status', table_name='sandbox_runs')
    op.drop_index('ix_sandbox_runs_patch_set_id', table_name='sandbox_runs')
    op.drop_table('sandbox_runs')
    op.drop_index('ix_patch_sets_status', table_name='patch_sets')
    op.drop_index('ix_patch_sets_run_id', table_name='patch_sets')
    op.drop_table('patch_sets')
    op.drop_index('ix_evidence_items_type', table_name='evidence_items')
    op.drop_index('ix_evidence_items_run_id', table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index('ix_analysis_steps_run_id', table_name='analysis_steps')
    op.drop_table('analysis_steps')
    op.drop_index('ix_code_chunks_symbol', table_name='code_chunks')
    op.drop_index('ix_code_chunks_file_id', table_name='code_chunks')
    op.drop_table('code_chunks')
    op.drop_index('ix_analysis_runs_status', table_name='analysis_runs')
    op.drop_index('ix_analysis_runs_incident_id', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index('ix_import_jobs_status', table_name='repository_import_jobs')
    op.drop_index('ix_import_jobs_repo_id', table_name='repository_import_jobs')
    op.drop_table('repository_import_jobs')
    op.drop_index('ix_repository_files_repo_path', table_name='repository_files')
    op.drop_index('ix_repository_files_repo_id', table_name='repository_files')
    op.drop_table('repository_files')
    op.drop_index('ix_incidents_workspace_id', table_name='incidents')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_severity', table_name='incidents')
    op.drop_index('ix_incidents_created_by', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_workspace_members_ws_user', table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('ix_repositories_ws_fullname', table_name='repositories')
    op.drop_index('ix_repositories_workspace_id', table_name='repositories')
    op.drop_table('repositories')
    op.drop_index('ix_audit_events_workspace_id', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_id', table_name='audit_events')
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_workspaces_slug', table_name='workspaces')
    op.drop_index('ix_workspaces_owner_id', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_oauth_provider_user', table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
